subdir-ccflags-y += -Wno-error
ccflags-y += -Wno-unused-variable -g
ccflags-y += -Wno-unused-function -g

ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/alsps/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/hwmon/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/mt6580/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/mt6580/include/mach

obj-y	:=  cm36283.o

